### ISSUE TITLE
error in step 4

### ISSUE THREAD

**Issue by michael-7845** [DiUS/pact-workshop-jvm#3]
Hi uglyog,
I follow the workshop smoothly until step 4:
it seems that pactVerify task isn't run to check pact here.
Thanks a lot!

-------------------------------------------------------------------------------
gradlew :providers:springboot-provider:pactVerify
...
2017-07-18 18:28:11.699  INFO 26756 --- [           main] .s.b.c.e.j.JettyEmbeddedServletContainer : Jetty started on port(s) 8080 (http/1.1)
2017-07-18 18:28:11.707  INFO 26756 --- [           main] a.c.d.p.s.MainApplication                : Started MainApplication in 9.825 seconds (JVM running for 11.318)
java -jar C:\github\pact-workshop-jvm\providers\springboot-provider\build\libs\springboot-provider.jar is ready.
:providers:springboot-provider:startProvider FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':providers:springboot-provider:startProvider'.
> java.lang.NoSuchFieldException: pid

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.886 secs

**Comment by uglyog** [comment]
Haven't tested it on Windows. Looks like the spawn plugin does not work on Windows.

Could you run the workshop in a Linux VM?

**Comment by michael-7845** [comment]
thanks!

I'll have a try.


________________________________
发件人: Ronald Holshausen <notifications@github.com>
发送时间: 2017年8月3日 14:37
收件人: DiUS/pact-workshop-jvm
抄送: 虞科敏; Author
主题: Re: [DiUS/pact-workshop-jvm] error in step 4 (#3)


Haven't tested it on Windows. Looks like the spawn plugin does not work on Windows.

Could you run the workshop in a Linux VM?

―

**Comment by StevePolingOfExcelon** [comment]
I'm running OSX (this might be a different problem than described above) and I'm a total gradle & springbook virgin. My difficulty at Step 4 was a fight between gradle and springboot. Fix was to change providers/springboot-provider/build.gradle to say id "au.com.dius.pact" version "3.6.6."

Apparently earlier versions of the plug-in failed to cast a GStringImpl variable (arising from 'Our_Provider') to a righteous Java string that Gradle's NameValidator.asValidName() could digest.

I think the righteous fix to this issue is to carefully track proven-good versions of the tools and/or update to the latest-greatest as soon as they can be verified.

**Comment by uglyog** [comment]
I've updated to the latest Pact-JVM version (4.1.2)
